FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TimLearning.DockerManager.Api/TimLearning.DockerManager.Api.csproj", "TimLearning.DockerManager.Api/"]
COPY ["TimLearning.DockerManager.ApiClient/TimLearning.DockerManager.ApiClient.csproj", "TimLearning.DockerManager.ApiClient/"]
COPY ["TimLearning.Shared/TimLearning.Shared.csproj", "TimLearning.Shared/"]
RUN dotnet restore "TimLearning.DockerManager.Api/TimLearning.DockerManager.Api.csproj"
COPY . .
WORKDIR "/src/TimLearning.DockerManager.Api"
RUN dotnet build "TimLearning.DockerManager.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "TimLearning.DockerManager.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TimLearning.DockerManager.Api.dll"]
