version: "3"

services:
  server:
    container_name: "server"
    build: ../server/TimLearning
    environment:
      - DataEncryptor__SharedKey=${API_DATA_ENCRYPTOR_SHARED_KEY}
      - DbConnectionStrings__Postgres=${API_POSTGRES_CONNECTION}
      - TimLearningSite__Url=${API_TIM_LEARNING_URL}
      - Mail__Server=${API_MAIL_SERVER}
      - Mail__Port=${API_MAIL_PORT}
      - Mail__UserName=${API_MAIL_USER_NAME}
      - Mail__UserMail=${API_MAIL_USER_MAIL}
      - Mail__Password=${API_MAIL_PASSWORD}
      - Mail__UseSsl=${API_MAIL_USE_SSL}
      - JwtSecret__Key=${API_JWT_SECRET_KEY}
    ports:
      - ${API_HTTP_PORT}:8080
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: "frontend"
    build:
      args:
        - REACT_APP_API_URL=${FRONTEND_API_URL}
      context: ../client
      dockerfile: dockerfile
    ports:
      - ${FRONTEND_PUBLIC_PORT}:${FRONTEND_INTERNAL_PORT}
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf

  postgres:
    container_name: "postgres"
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_PUBLIC_PORT}:${POSTGRES_INTERNAL_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db-data:
