services:
  server:
    container_name: "server"
    build:
      context: ../server/TimLearning
      dockerfile: Dockerfile
    environment:
      - Broker__Host=rabbitmq
    ports:
      - ${API_HTTP_PORT}:80
      - ${API_HTTPS_PORT}:443
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: "frontend"
    build:
      context: ./src/frontend/
      dockerfile: chat/dockerfile
    ports:
      - ${FRONTEND_LOCAL_PORT}:${FRONTEND_DOCKER_PORT}
    volumes:
      - ./src/frontend/chat/src:/app/src

  postgres:
    container_name: "postgres"
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
